### ISSUE TITLE
syntax for setting ElectrodeConnection and set_channel_configuration

### ISSUE THREAD

**Issue by Cdriko** [bicarlsen/easy-biologic#13]
Hello
I whant to set both Electrode connection to STANDARD  and channel 6 hardware configuration to FLOATING, and I'm not sure to understand the syntax.
Is the following is good ?

```
import easy_biologic as ebl

bl = ebl.BiologicDevice( '192.168.1.2' )

bl.set_channel_configuration(5,FLOATING,STANDARD)
```

thanks

**Comment by bicarlsen** [comment]
It is best to use the enums [`easy_biologic.lib.ec_lib.ElectrodeConnection`](https://github.com/bicarlsen/easy-biologic/blob/81dc00692a008111d367f0643f15b9096ea2a23c/easy_biologic/lib/ec_lib.py#L226) and [`easy_biologic.lib.ec_lib.ChannelMode`](https://github.com/bicarlsen/easy-biologic/blob/81dc00692a008111d367f0643f15b9096ea2a23c/easy_biologic/lib/ec_lib.py#L231) for this.

e.g.
```python
from easy_biologic.device as BiologicDevice
from easy_biologic.lib.ec_lib import ChannelMode, ElectrodeConnection

bl = BiologicDevice( '192.168.1.2' )
bl.set_channel_configuration( 5,  ChannelMode.FLOATING, ElectrodeConnection.STANDARD )
```

**Comment by Cdriko** [comment]
thanks, I try that but get an error :
```
  bl.set_channel_configuration( 5,  ChannelMode.GROUNDED , ElectrodeConnection.STANDARD )
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\easy_biologic\device.py", line 263, in set_channel_configuration
    raise RuntimeError( 'Hardware configuration is only available for SP-300 devices.' )
RuntimeError: Hardware configuration is only available for SP-300 devices.
```

But it's a VSP300 : 
`kind : DeviceCodes.KBIO_DEV_VSP300`

**Comment by bicarlsen** [comment]
As the error says you can only set these parameter on `SP-300` devices. This is a limitation of the hardware, not this package.
