### ISSUE TITLE
Potentiostat version

### ISSUE THREAD

**Issue by ThomasHolmIFE** [bicarlsen/easy-biologic#15]
Hi, I am testing the program to run a VSP-300 potentiostat. This is a class SP-300 potentiostat, but due to it being identified as a type: KBIO_DEV_VSP300, it will be identified as a VMP3 system (i.e., not KBIO-DEV_VSP300) when loading the *.ecc files in the base_programs.py. This should thus be the *4.ecc files and not *.ecc. Is there a way to override this so the correct identification/class occurs?

Relevant code: line 425:
"self._data_fields = (
            dp.SP300_Fields.OCV
            if self.device.kind is ecl.DeviceCodes.KBIO_DEV_SP300 else
            dp.VMP3_Fields.OCV
        )"

**Comment by ThomasHolmIFE** [comment]
I see now that this is the same issue as Cdriko.

**Comment by bicarlsen** [comment]
Thanks for bringing that up as well. Perhaps you could pull [@Cdriko's update](https://github.com/bicarlsen/easy-biologic/pull/14) and test it out before I pull it into the main code base.

**Comment by ThomasHolmIFE** [comment]
Hi bicarlsen,

I am not the most experienced user with github, but after cloning the package locally with Cdriko’s changes, I am able to successfully run a simple OCV and a CA program on my potentiostat (VSP-300). Thus, the fix fixes the potentiostat class problem and works fine for this.

Btw, thanks for putting in all the work in making the easy-biologic package! It is much appreciated!

Cheers,
Thomas

**Comment by bicarlsen** [comment]
I updated @Cdriko's code a bit in Pull Request #16. If you have a chance to test out the updated code it would be greatly appreciated.

**Comment by ThomasHolmIFE** [comment]
Hey,

I can do this as soon as I make it to work again where the instrument is. I currently have corona, so don’t expect anything before Friday at the earliest.

Thomas

**Comment by ThomasHolmIFE** [comment]
Hi bicarlsen,

I have tested the latest version now, and it seems to work as intended with a very simple program (connect to VSP-300, run a single technique (CA), and print data in cmd).

Cheers,
Thomas

**Comment by bicarlsen** [comment]
Awesome :) Thanks so much. I should update the package in the coming days then.

**Comment by bicarlsen** [comment]
These changes have been added in [easy-biologic v0.3.3](https://pypi.org/project/easy-biologic/0.3.3/).
