### ISSUE TITLE
PEIS params : duration

### ISSUE THREAD

**Issue by Cdriko** [bicarlsen/easy-biologic#17]
Hello
I don't understand the 
["duration" parameter of a PEIS technique](https://github.com/bicarlsen/easy-biologic/blob/main/README.md#params-3).

It doesn't appears in  EC-lab development package doc  : 
In this doc there is 

vs_initial
vs_final
initial_voltage_step
final_voltage_step
duration_step
step_number
record_every_dT
record_every_dI
final_frequency
initial_frequency
sweep
Amplitude_Voltage
Frequency_number
Average_N_times
Correction
Wait_for_steady

Can you explain how this parameter works ?
It seems to be a timeout like, but it's difficult to estimate the duration of this kind of technique.

Thanks

**Comment by Cdriko** [comment]
I trys following settings (inxml in my soft) but a can't get more than 4 frequency result, despite that I set 10 points by decade.

```
<amplitude_voltage>0.1</amplitude_voltage>
<initial_frequency>1000000</initial_frequency>
<final_frequency>0.1</final_frequency>
<time_interval>1.5</time_interval>
<voltage>0</voltage>
<frequency_number>10</frequency_number>
<average_n_times>2</average_n_times>
<duration>1000</duration>
```

**Comment by bicarlsen** [comment]
The `duration` parameter maps to the `Duration_step` PEIS parameter (Sec. 7.11.2 in the EC-Lab Development Package
User's Guide Version 6.00 – April 2017) which has the description of "Step duration in seconds". Does that help answer the question?

**Comment by bicarlsen** [comment]
Due to the lack of activity in this thread I will close it. However, if you have any other issues, please feel free to open a new issue.
