### ISSUE TITLE
Not an issue, but a question about techniques

### ISSUE THREAD

**Issue by ThomasHolmIFE** [bicarlsen/easy-biologic#20]
I haven't checked to carefully, but as I remember from EC-lab documentation there is some limit to which techniques that can be implemented (not PEIS with multisine option for example). Do you know if this is the case for adding the GEIS technique (Galvanostatic Electrochemical Impedance Spectroscopy)? If it is possible, I can give it a try to add it.

**Comment by ThomasHolmIFE** [comment]
Hi, I've given this a try and added a pull request for adding the tecnhique. Please look through the formatting etc to unify with the rest of the code. 

I also had a test script, which was also added, but shouldn't be part of the main branch. Not sure how to remove it without also removing it locally.

**Comment by ThomasHolmIFE** [comment]
The technique has been tested locally here with a VSP-300 system. It would probably be worthwhile to test also on other systems, but with the addition of the instrument classes in February, I think this should work well then as well.

**Comment by bicarlsen** [comment]
These changes are included in [version 0.3.4](https://github.com/bicarlsen/easy-biologic/releases/tag/0.3.4).
