### ISSUE TITLE
USB connection is not possible

### ISSUE THREAD

**Issue by AznIQ** [bicarlsen/easy-biologic#3]
Connection via USB is not possible, whereas connection via LAN works.
Using find_devices.py with USB connection doesn't work and doesn't display a device name or port. With LAN the script shows the IP address.

Not possible to create device by ebl.BiologicDevice('USB0'). 

Biologic USB driver was installed. EC-lab software detects the USB port, once one installed the driver. With the EC-Lab software it is possible to control the potentiostat via USB (already tried out). Used Biologic's VMP3 potentiostat.

**Comment by bicarlsen** [comment]
This issue is fixed in the new version (v0.3.0) which will be released shortly. The issue was in the EC Lab Developers Kit (EDK) v6.0.1, which has been fixed in v6.0.4. In v0.3.0, EDK c6.0.4 is the default library.

**Comment by AznIQ** [comment]
Hi, this is cool! I will try it out

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by bicarlsen** [comment]
The new version of [`easy_biologic v0.3.0`](https://pypi.org/project/easy-biologic/) has been relased.
